# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ruverse < Formula
  desc "Control connected personal agents on RUverse"
  homepage "https://ruverse.ai"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RUverse/ruverse-cli/releases/download/v1.0.0/ruverse_1.0.0_darwin_amd64.tar.gz"
      sha256 "390a450aaf58eafae5cb906f5d9c5037249e00f17ef48252a276ee21e9f03ea7"

      define_method(:install) do
        bin.install "ruverse"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RUverse/ruverse-cli/releases/download/v1.0.0/ruverse_1.0.0_darwin_arm64.tar.gz"
      sha256 "3eed7d20ec185d2bdbb079d1f1fbc14b51a03287c53fe6d746fa2cca3f1c15f3"

      define_method(:install) do
        bin.install "ruverse"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/RUverse/ruverse-cli/releases/download/v1.0.0/ruverse_1.0.0_linux_amd64.tar.gz"
      sha256 "55b807da15faac722ad1431b598a02cfa762aca69a0f2be57515b21476753702"
      define_method(:install) do
        bin.install "ruverse"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RUverse/ruverse-cli/releases/download/v1.0.0/ruverse_1.0.0_linux_arm64.tar.gz"
      sha256 "677f6909d124b0c31fb1781375ee2bd8b01515a266d0c4dda130888be99cd245"
      define_method(:install) do
        bin.install "ruverse"
      end
    end
  end

  test do
    system "#{bin}/ruverse", "version"
  end
end
