# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ruverse < Formula
  desc "Control connected personal agents on RUverse"
  homepage "https://ruverse.ai"
  version "1.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RUverse/ruverse-cli/releases/download/v1.0.1/ruverse_1.0.1_darwin_amd64.tar.gz"
      sha256 "a371c61f68c2b131d22aabf62678d42fef36347ce2fb48e3a8e12c62532cf10d"

      define_method(:install) do
        bin.install "ruverse"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RUverse/ruverse-cli/releases/download/v1.0.1/ruverse_1.0.1_darwin_arm64.tar.gz"
      sha256 "20cfa70fe9a10f2b5e12b965428b610837001184f6831097260535afeca7c025"

      define_method(:install) do
        bin.install "ruverse"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/RUverse/ruverse-cli/releases/download/v1.0.1/ruverse_1.0.1_linux_amd64.tar.gz"
      sha256 "0aa8a6a061ff59a403c108bd9a8019b8a50d95432198b44fba373058eead2c76"
      define_method(:install) do
        bin.install "ruverse"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RUverse/ruverse-cli/releases/download/v1.0.1/ruverse_1.0.1_linux_arm64.tar.gz"
      sha256 "e5c61a7c22a5ae7c8b1eea0ae0316c60bf5c094e4386268f10f4273547401ada"
      define_method(:install) do
        bin.install "ruverse"
      end
    end
  end

  test do
    system "#{bin}/ruverse", "version"
  end
end
